default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"]%>
  password: <%= ENV["DB_PASSWORD"] %> #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workout_development

test:
  <<: *default
  database: workout_development_test

production:
  <<: *default
  database: workout_development_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
